version: '3.4'
services:
  frontend:
    build:
      context: docker/frontend
      network: host
#    ports:
#      - 8080:8080
    volumes:
      - ./:/project
    working_dir: /project/frontend
    networks:
      - chcepograc-net
    command: "webpack --watch"
    tty: true
#  backend:
#    build: docker/backend
#    ports:
#      - ${BACKEND_PORT}:8080
#    volumes:
#      - ./:/project
#    working_dir: /project
#    networks:
#      - chcepograc-net
#    command: "java -jar /project/out/artifacts/chcepograc_jar/app.jar"
  db:
    image: postgres:alpine
    restart: always
    ports:
      - ${DB_PORT}:5432
    volumes:
      - ${DB_STORAGE}:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
    networks:
      - chcepograc-net
networks:
  chcepograc-net:
    driver: bridge