---

- name: Add Java8 Repository
  become: yes
  apt_repository: repo="ppa:webupd8team/java"

- name: Autoaccept license for Java
  become: yes
  debconf: name="oracle-java8-installer" question="shared/accepted-oracle-license-v1-1" value="true" vtype="select"

- name: Install Java8
  become: yes
  apt: name={{item}} update_cache=yes force=yes state=latest
  with_items:
    - oracle-java8-installer
    - oracle-java8-set-default
    - maven
